title:         David Miller
description:   The official blog of David Miller, creator of Start Bootstrap
baseurl:       ""
url:           ""

# Build settings
markdown:      kramdown
paginate:      5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
